# Generated by Django 5.2.5 on 2025-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='topic',
            field=models.CharField(choices=[('business', 'Business'), ('travel', 'Travel'), ('daily', 'Daily')], default='daily', max_length=64),
        ),
    ]
