# Generated by Django 5.2.5 on 2025-10-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0002_alter_phrase_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='repeat_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of times to repeat each video (1-10)'),
        ),
    ]
