# Generated by Django 5.2.4 on 2025-10-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='scene_image_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expression',
            name='video_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
    ]
