# Generated by Django 5.2.5 on 2025-10-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0006_expression_scene_image_key_expression_video_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='topic',
            field=models.CharField(choices=[('business', 'Business'), ('travel', 'Travel'), ('daily', 'Daily'), ('shopping', 'Shopping')], default='daily', max_length=64),
        ),
    ]
