# Generated by Django 5.2.5 on 2025-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0007_alter_phrase_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='repeat_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of times to repeat each video (1-10)'),
        ),
    ]
